# Generated by Django 5.1.4 on 2025-01-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=10)),
                ('jam', models.TimeField()),
                ('matkul', models.CharField(max_length=50)),
                ('dosen', models.CharField(max_length=75)),
                ('ruang', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='mahasiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nim', models.CharField(max_length=10)),
                ('nama', models.CharField(max_length=50)),
                ('prodi', models.CharField(max_length=50)),
                ('semester', models.CharField(max_length=4)),
            ],
        ),
    ]
