# Generated by Django 5.1.4 on 2025-01-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_jadwal_semester_alter_jadwal_hari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwal',
            name='semester',
            field=models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8')]),
        ),
    ]
